
unsigned long IT32_ChooseColorA();
unsigned long ChooseColor();
unsigned long IT32_ChooseFontA();
unsigned long ChooseFont();
unsigned long IT32_CommDlgExtendedError();
unsigned long CommDlgExtendedError();
unsigned long IT32_FindTextA();
unsigned long FindText();
unsigned long IT32_GetFileTitleA();
unsigned long GetFileTitle();
unsigned long IT32_GetOpenFileNameA();
unsigned long GetOpenFileName();
unsigned long IT32_GetSaveFileNameA();
unsigned long GetSaveFileName();
unsigned long IT32_PrintDlgA();
unsigned long PrintDlg();
unsigned long IT32_ReplaceTextA();
unsigned long ReplaceText();
